# Generated by Django 4.1.3 on 2022-11-28 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 28, 21, 18, 2, 396092, tzinfo=datetime.timezone.utc), verbose_name='Fecha de Publicación'),
        ),
    ]
