# Generated by Django 4.1.3 on 2022-11-28 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 28, 21, 21, 46, 759492, tzinfo=datetime.timezone.utc), verbose_name='Fecha de Publicación'),
        ),
    ]
